services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./.ollama:/root/.ollama
    ports:
      - "11434:11434"  # Проброс порта 11434
    restart: unless-stopped