services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    volumes:
      - ./.ollama:/root/.ollama
    ports:
      - "11434:11434"  # Проброс порта 11434
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]